# Description: Configuration file for the Google BeReal Alarm 
# Author: Jorick Bouw
# Author URL:
# https://github.com/jorickjuh
# Documentation:
# https://github.com/jorickjuh/Google-BeReal-Alarm/wiki/Getting-it-Up-and-Running
debug: false # Set to true to enable debug mode
bereal:
    bereal_time_history_api: 0b4f65d7-fee2-4996-8bbd-007147a2b373
    region: europe-west # us-central, europe-west, asia-west, asia-east
    time_zone: 2 # Timezone of your location in UTC+X format. So for the Netherlands it would be 2
google:
    device_name: all # Device name or Group name in Google Home App 
    alarm_url: https://dx35vtwkllhj9.cloudfront.net/universalstudios/super-mario-bros-plumbing/images/soundbites/completion-audio.mp3 # Can not use local files. Can only play uploaded sound files for example:(https://example.com/example.mp3)